import { Customer, Worker, Ticket, TicketEvent } from "../types/index";

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    full_name: "Ahmed Al Mansoori",
    email: "ahmed.mansoori@email.com",
    phone: "+971501234567",
    property_ref: "Villa-12",
    building_name: "Al Reef Villas",
    floor: null,
    unit_number: "Villa 12",
    area: "Khalifa City",
    city: "Abu Dhabi",
    emergency_contact: "+971509876543",
    contract_expiry: "2026-12-31",
    preferred_contact: "whatsapp",
  },
  {
    id: "c2",
    full_name: "Sara Ibrahim",
    email: "sara.ibrahim@email.com",
    phone: "+971502345678",
    property_ref: "Apt-B7",
    building_name: "The Greens Tower B",
    floor: "7th Floor",
    unit_number: "Apt B7",
    area: "Al Barsha",
    city: "Dubai",
    emergency_contact: null,
    contract_expiry: "2026-04-05",
    preferred_contact: "email",
  },
  {
    id: "c3",
    full_name: "Omar Farooq",
    email: "omar.farooq@email.com",
    phone: "+971503456789",
    property_ref: "Villa-34",
    building_name: "Bloom Gardens",
    floor: null,
    unit_number: "Villa 34",
    area: "Khalifa City",
    city: "Abu Dhabi",
    emergency_contact: "+971508765432",
    contract_expiry: "2027-01-15",
    preferred_contact: "phone",
  },
  {
    id: "c4",
    full_name: "Fatima Noor",
    email: "fatima.noor@email.com",
    phone: "+971504567890",
    property_ref: "Apt-C3",
    building_name: "Reva Residences",
    floor: "3rd Floor",
    unit_number: "Apt C3",
    area: "Al Reem Island",
    city: "Abu Dhabi",
    emergency_contact: null,
    contract_expiry: "2026-03-28",
    preferred_contact: "whatsapp",
  },
  {
    id: "c5",
    full_name: "Rania Hassan",
    email: "rania.hassan@email.com",
    phone: "+971505678901",
    property_ref: "Villa-08",
    building_name: "Mirdif Villas",
    floor: null,
    unit_number: "Villa 8",
    area: "Mirdif",
    city: "Dubai",
    emergency_contact: "+971507654321",
    contract_expiry: "2026-09-30",
    preferred_contact: "email",
  },
  {
    id: "c6",
    full_name: "Yousef Al Zaabi",
    email: "yousef.zaabi@email.com",
    phone: "+971506789012",
    property_ref: "Apt-D11",
    building_name: "Sharjah Gate Towers",
    floor: "11th Floor",
    unit_number: "Apt D11",
    area: "Sharjah Al Majaz",
    city: "Sharjah",
    emergency_contact: null,
    contract_expiry: "2026-07-20",
    preferred_contact: "phone",
  },
  {
    id: "c7",
    full_name: "Layla Mahmoud",
    email: "layla.mahmoud@email.com",
    phone: "+971507890123",
    property_ref: "Villa-21",
    building_name: "Jumeirah Park Villas",
    floor: null,
    unit_number: "Villa 21",
    area: "Jumeirah",
    city: "Dubai",
    emergency_contact: "+971506543210",
    contract_expiry: "2026-04-10",
    preferred_contact: "whatsapp",
  },
  {
    id: "c8",
    full_name: "Bilal Qureshi",
    email: "bilal.qureshi@email.com",
    phone: "+971508901234",
    property_ref: "Apt-A2",
    building_name: "Silicon Heights",
    floor: "2nd Floor",
    unit_number: "Apt A2",
    area: "Dubai Silicon Oasis",
    city: "Dubai",
    emergency_contact: null,
    contract_expiry: "2027-03-01",
    preferred_contact: "email",
  },
  {
    id: "c9",
    full_name: "Mariam Al Ketbi",
    email: "mariam.ketbi@email.com",
    phone: "+971509012345",
    property_ref: "Villa-55",
    building_name: "Al Nahda Gardens",
    floor: null,
    unit_number: "Villa 55",
    area: "Al Nahda",
    city: "Sharjah",
    emergency_contact: "+971505432109",
    contract_expiry: "2026-11-15",
    preferred_contact: "phone",
  },
  {
    id: "c10",
    full_name: "Tariq Bin Zayed",
    email: "tariq.binzayed@email.com",
    phone: "+971500123456",
    property_ref: "Apt-F6",
    building_name: "Bloom Heights",
    floor: "6th Floor",
    unit_number: "Apt F6",
    area: "Al Reem Island",
    city: "Abu Dhabi",
    emergency_contact: null,
    contract_expiry: "2026-08-22",
    preferred_contact: "whatsapp",
  },
];

export const mockWorkers: Worker[] = [
  { id: "w1", full_name: "Khalid Rashid",   skills: ["plumbing", "general"],    phone: "+971501111111", is_active: true,  open_tickets: 3 },
  { id: "w2", full_name: "Hassan Ali",      skills: ["electrical", "hvac"],     phone: "+971502222222", is_active: true,  open_tickets: 2 },
  { id: "w3", full_name: "Tariq Saeed",     skills: ["carpentry", "general"],   phone: "+971503333333", is_active: true,  open_tickets: 1 },
  { id: "w4", full_name: "Mohammed Nasser", skills: ["hvac", "plumbing"],       phone: "+971504444444", is_active: false, open_tickets: 0 },
];

export const mockTickets: Ticket[] = [
  {
    id: "t1",
    ticket_ref: "TKT-0001",
    customer_email: "ahmed.mansoori@email.com",
    worker_id: null,
    property: "Villa-12",
    job_type: "plumbing",
    urgency: "high",
    status: "OPEN",
    ai_summary: "Burst pipe under kitchen sink causing active water leakage onto floor. Tenant reports water spreading to adjacent cabinet.",
    eta_description: null,
    location_notes: "Kitchen, under the sink cabinet on the left side",
    access_instructions: "Key with building security. Tenant available after 6pm.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a1", url: "https://placehold.co/600x400/e2e8f0/475569?text=Burst+Pipe", file_type: "image", label: "Burst pipe photo", uploaded_by: "Ahmed Al Mansoori", uploaded_at: "2026-03-11T08:00:00Z" },
      { id: "a2", url: "https://placehold.co/600x400/e2e8f0/475569?text=Water+Damage", file_type: "image", label: "Water damage on floor", uploaded_by: "Ahmed Al Mansoori", uploaded_at: "2026-03-11T08:05:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-11T08:00:00Z",
    updated_at: "2026-03-11T08:00:00Z",
  },
  {
    id: "t2",
    ticket_ref: "TKT-0002",
    customer_email: "sara.ibrahim@email.com",
    worker_id: "w2",
    property: "Apt-B7",
    job_type: "electrical",
    urgency: "medium",
    status: "ASSIGNED",
    ai_summary: "Power outage in bedroom and living room. Circuit breaker trips every time lights are switched on in those rooms.",
    eta_description: "Within 24 hours",
    location_notes: "Fuse box is in the utility closet near the entrance",
    access_instructions: "Tenant Sara works from home, available any time. Call ahead 30 mins.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a3", url: "https://placehold.co/600x400/e2e8f0/475569?text=Fuse+Box", file_type: "image", label: "Tripped circuit breaker", uploaded_by: "Sara Ibrahim", uploaded_at: "2026-03-13T07:30:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-13T09:00:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-13T07:30:00Z",
    updated_at: "2026-03-13T09:00:00Z",
  },
  {
    id: "t3",
    ticket_ref: "TKT-0003",
    customer_email: "omar.farooq@email.com",
    worker_id: "w2",
    property: "Villa-34",
    job_type: "hvac",
    urgency: "low",
    status: "IN_PROGRESS",
    ai_summary: "AC unit in master bedroom not cooling effectively. Room temperature stays above 28°C even on full blast. Filter likely blocked.",
    eta_description: "Today afternoon",
    location_notes: "Master bedroom, wall-mounted unit above wardrobe",
    access_instructions: "Gate code is 4521. Tenant Omar is home all day.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a4", url: "https://placehold.co/600x400/e2e8f0/475569?text=AC+Unit", file_type: "image", label: "AC unit master bedroom", uploaded_by: "Omar Farooq", uploaded_at: "2026-03-12T10:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-12T10:30:00Z",
    in_progress_at: "2026-03-13T08:00:00Z",
    done_at: null,
    created_at: "2026-03-12T10:00:00Z",
    updated_at: "2026-03-13T08:00:00Z",
  },
  {
    id: "t4",
    ticket_ref: "TKT-0004",
    customer_email: "fatima.noor@email.com",
    worker_id: "w3",
    property: "Apt-C3",
    job_type: "carpentry",
    urgency: "low",
    status: "COMPLETED",
    ai_summary: "Broken cabinet door hinge in master bedroom wardrobe. Door hanging loose and cannot be closed properly.",
    eta_description: "Next business day",
    location_notes: "Master bedroom, rightmost wardrobe door",
    access_instructions: "Tenant Fatima works mornings. Best time is after 1pm.",
    reported_via: "manual",
    resolution_notes: "Replaced both hinges on the wardrobe door. Door closes and locks properly. Tenant confirmed satisfied.",
    attachments: [
      { id: "a5", url: "https://placehold.co/600x400/e2e8f0/475569?text=Broken+Hinge", file_type: "image", label: "Broken hinge before repair", uploaded_by: "Fatima Noor", uploaded_at: "2026-03-11T09:00:00Z" },
    ],
    completion_photos: [
      { id: "a6", url: "https://placehold.co/600x400/94a3b8/ffffff?text=Fixed+Hinge", file_type: "image", label: "Repaired hinge", uploaded_by: "Tariq Saeed", uploaded_at: "2026-03-12T14:00:00Z" },
    ],
    assigned_at: "2026-03-11T09:15:00Z",
    in_progress_at: "2026-03-12T10:00:00Z",
    done_at: "2026-03-12T14:00:00Z",
    created_at: "2026-03-11T09:00:00Z",
    updated_at: "2026-03-12T14:00:00Z",
  },
  {
    id: "t5",
    ticket_ref: "TKT-0005",
    customer_email: "rania.hassan@email.com",
    worker_id: "w1",
    property: "Villa-08",
    job_type: "plumbing",
    urgency: "high",
    status: "ASSIGNED",
    ai_summary: "Main bathroom drain completely blocked. Water backing up into shower and flooding bathroom floor.",
    eta_description: "Within 4 hours",
    location_notes: "Main bathroom, floor drain next to shower",
    access_instructions: "Spare key with neighbour in Villa 9. Tenant Rania reachable on WhatsApp.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a7", url: "https://placehold.co/600x400/e2e8f0/475569?text=Blocked+Drain", file_type: "image", label: "Blocked drain flooding", uploaded_by: "Rania Hassan", uploaded_at: "2026-03-13T08:45:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-13T09:30:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-13T08:45:00Z",
    updated_at: "2026-03-13T09:30:00Z",
  },
  {
    id: "t6",
    ticket_ref: "TKT-0006",
    customer_email: "yousef.zaabi@email.com",
    worker_id: null,
    property: "Apt-D11",
    job_type: "general",
    urgency: "medium",
    status: "OPEN",
    ai_summary: "Front door lock jammed. Tenant unable to lock from outside. Security risk as unit on 11th floor facing main corridor.",
    eta_description: null,
    location_notes: "Main entrance door, deadbolt mechanism",
    access_instructions: "Building management has master key. Yousef works nights, do not visit before 12pm.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a8", url: "https://placehold.co/600x400/e2e8f0/475569?text=Door+Lock", file_type: "image", label: "Jammed door lock", uploaded_by: "Yousef Al Zaabi", uploaded_at: "2026-03-13T09:15:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-13T09:15:00Z",
    updated_at: "2026-03-13T09:15:00Z",
  },
  {
    id: "t7",
    ticket_ref: "TKT-0007",
    customer_email: "layla.mahmoud@email.com",
    worker_id: "w2",
    property: "Villa-21",
    job_type: "electrical",
    urgency: "high",
    status: "IN_PROGRESS",
    ai_summary: "Exposed wiring found in utility room behind washing machine. Wires frayed and touching wall. Potential fire hazard.",
    eta_description: "Within 2 hours",
    location_notes: "Utility room, behind the washing machine on the right wall",
    access_instructions: "Gate is always open. Layla is home. Mark as urgent on arrival.",
    reported_via: "phone",
    resolution_notes: null,
    attachments: [
      { id: "a9", url: "https://placehold.co/600x400/fecaca/991b1b?text=Exposed+Wiring", file_type: "image", label: "Exposed frayed wires", uploaded_by: "Layla Mahmoud", uploaded_at: "2026-03-11T07:00:00Z" },
      { id: "a10", url: "https://placehold.co/600x400/fecaca/991b1b?text=Fire+Risk+Area", file_type: "image", label: "Area near wiring", uploaded_by: "Layla Mahmoud", uploaded_at: "2026-03-11T07:05:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-11T07:15:00Z",
    in_progress_at: "2026-03-13T08:00:00Z",
    done_at: null,
    created_at: "2026-03-11T07:00:00Z",
    updated_at: "2026-03-13T08:00:00Z",
  },
  {
    id: "t8",
    ticket_ref: "TKT-0008",
    customer_email: "bilal.qureshi@email.com",
    worker_id: "w2",
    property: "Apt-A2",
    job_type: "hvac",
    urgency: "medium",
    status: "COMPLETED",
    ai_summary: "Heating unit making loud rattling noise during operation. Noise starts 10 minutes after turning on and persists.",
    eta_description: "Within 24 hours",
    location_notes: "Living room ceiling unit",
    access_instructions: "Bilal works remotely, home all day. Prefers morning visits.",
    reported_via: "email",
    resolution_notes: "Fan blade was loose causing vibration and rattling. Tightened blade assembly and lubricated motor bearings. Unit now operating quietly.",
    attachments: [
      { id: "a11", url: "https://placehold.co/600x400/e2e8f0/475569?text=HVAC+Unit", file_type: "image", label: "Noisy HVAC unit", uploaded_by: "Bilal Qureshi", uploaded_at: "2026-03-10T11:00:00Z" },
    ],
    completion_photos: [
      { id: "a12", url: "https://placehold.co/600x400/94a3b8/ffffff?text=Fixed+HVAC", file_type: "image", label: "Repaired fan assembly", uploaded_by: "Hassan Ali", uploaded_at: "2026-03-11T13:00:00Z" },
    ],
    assigned_at: "2026-03-10T11:30:00Z",
    in_progress_at: "2026-03-10T15:00:00Z",
    done_at: "2026-03-11T13:00:00Z",
    created_at: "2026-03-10T11:00:00Z",
    updated_at: "2026-03-11T13:00:00Z",
  },
  {
    id: "t9",
    ticket_ref: "TKT-0009",
    customer_email: "mariam.ketbi@email.com",
    worker_id: null,
    property: "Villa-55",
    job_type: "carpentry",
    urgency: "low",
    status: "OPEN",
    ai_summary: "Wardrobe sliding door has come off its track in second bedroom. Door cannot be moved and is blocking access to wardrobe.",
    eta_description: null,
    location_notes: "Second bedroom, built-in wardrobe sliding door",
    access_instructions: "Call Mariam 1 hour before. Property has a dog — knock loudly.",
    reported_via: "manual",
    resolution_notes: null,
    attachments: [
      { id: "a13", url: "https://placehold.co/600x400/e2e8f0/475569?text=Wardrobe+Door", file_type: "image", label: "Door off track", uploaded_by: "Mariam Al Ketbi", uploaded_at: "2026-03-12T14:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-12T14:00:00Z",
    updated_at: "2026-03-12T14:00:00Z",
  },
  {
    id: "t10",
    ticket_ref: "TKT-0010",
    customer_email: "tariq.binzayed@email.com",
    worker_id: "w1",
    property: "Apt-F6",
    job_type: "plumbing",
    urgency: "medium",
    status: "ASSIGNED",
    ai_summary: "Water heater not producing consistent hot water. Water runs warm for 2 minutes then turns cold. Issue recurring since last month.",
    eta_description: "Tomorrow morning",
    location_notes: "Utility cupboard next to bathroom, white tank unit",
    access_instructions: "Tariq is available after 5pm weekdays. Building concierge has spare key.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a14", url: "https://placehold.co/600x400/e2e8f0/475569?text=Water+Heater", file_type: "image", label: "Water heater unit", uploaded_by: "Tariq Bin Zayed", uploaded_at: "2026-03-12T16:30:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-13T09:00:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-12T16:30:00Z",
    updated_at: "2026-03-13T09:00:00Z",
  },
];

export const mockTicketEvents: TicketEvent[] = [
  // TKT-0001
  { id: "e1",  ticket_id: "t1", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: plumbing, Urgency: high.",      created_at: "2026-03-11T08:01:00Z" },
  { id: "e2",  ticket_id: "t1", event_type: "NOTE",          actor: "Manager",       note: "Called tenant. Water shutoff valve closed temporarily to stop leak. Awaiting worker assignment.", created_at: "2026-03-11T08:30:00Z" },
  { id: "e3",  ticket_id: "t1", event_type: "NOTE",          actor: "Manager",       note: "No available plumber today. Escalated for tomorrow morning slot. Tenant informed.", created_at: "2026-03-11T17:00:00Z" },

  // TKT-0002
  { id: "e4",  ticket_id: "t2", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: electrical, Urgency: medium.",   created_at: "2026-03-13T07:31:00Z" },
  { id: "e5",  ticket_id: "t2", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali. ETA within 24 hours.",                                created_at: "2026-03-13T09:00:00Z" },
  { id: "e6",  ticket_id: "t2", event_type: "NOTE",          actor: "Hassan Ali",    note: "On my way to site. Estimated arrival in 45 minutes.",                          created_at: "2026-03-13T09:15:00Z" },
  { id: "e7",  ticket_id: "t2", event_type: "NOTE",          actor: "Manager",       note: "Tenant Sara confirmed she is home and ready for technician.",                  created_at: "2026-03-13T09:20:00Z" },

  // TKT-0003
  { id: "e8",  ticket_id: "t3", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp message. Job type: hvac, Urgency: low.",         created_at: "2026-03-12T10:01:00Z" },
  { id: "e9",  ticket_id: "t3", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali. Scheduled for this afternoon.",                        created_at: "2026-03-12T10:30:00Z" },
  { id: "e10", ticket_id: "t3", event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "Arrived on site. Filter is heavily blocked. Cleaning filter now.",             created_at: "2026-03-13T08:00:00Z" },
  { id: "e11", ticket_id: "t3", event_type: "NOTE",          actor: "Hassan Ali",    note: "Filter cleaned. Testing cooling performance. Will confirm fix in 30 minutes.", created_at: "2026-03-13T08:45:00Z" },

  // TKT-0004
  { id: "e12", ticket_id: "t4", event_type: "CREATED",       actor: "Manager",       note: "Ticket created manually by manager.",                                          created_at: "2026-03-11T09:01:00Z" },
  { id: "e13", ticket_id: "t4", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Tariq Saeed. Visit scheduled for next morning.",                   created_at: "2026-03-11T09:15:00Z" },
  { id: "e14", ticket_id: "t4", event_type: "NOTE",          actor: "Tariq Saeed",   note: "Tenant confirmed access for tomorrow at 10am.",                                created_at: "2026-03-11T14:00:00Z" },
  { id: "e15", ticket_id: "t4", event_type: "COMPLETED",     actor: "Tariq Saeed",   note: "Both hinges replaced. Door operates correctly. Tenant signed off on completion.", created_at: "2026-03-12T14:00:00Z" },

  // TKT-0005
  { id: "e16", ticket_id: "t5", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp. Job type: plumbing, Urgency: high.",             created_at: "2026-03-13T08:46:00Z" },
  { id: "e17", ticket_id: "t5", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Khalid Rashid as highest priority. ETA 4 hours.",                  created_at: "2026-03-13T09:30:00Z" },
  { id: "e18", ticket_id: "t5", event_type: "NOTE",          actor: "Khalid Rashid", note: "Confirmed with tenant. Heading to site now. Will need drain snake equipment.", created_at: "2026-03-13T09:45:00Z" },

  // TKT-0006
  { id: "e19", ticket_id: "t6", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: general, Urgency: medium.",      created_at: "2026-03-13T09:16:00Z" },
  { id: "e20", ticket_id: "t6", event_type: "NOTE",          actor: "Manager",       note: "Noted tenant works nights. Scheduling visit for after 12pm tomorrow.",         created_at: "2026-03-13T10:00:00Z" },
  { id: "e21", ticket_id: "t6", event_type: "NOTE",          actor: "Manager",       note: "Building management informed to ensure master key is available for technician.", created_at: "2026-03-13T10:05:00Z" },

  // TKT-0007
  { id: "e22", ticket_id: "t7", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from phone call log. Job type: electrical, Urgency: high.",    created_at: "2026-03-11T07:01:00Z" },
  { id: "e23", ticket_id: "t7", event_type: "ASSIGNED",      actor: "Manager",       note: "Marked critical. Assigned to Hassan Ali immediately.",                          created_at: "2026-03-11T07:15:00Z" },
  { id: "e24", ticket_id: "t7", event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "On site. Wiring is exposed and dangerous. Isolated the circuit for safety.",   created_at: "2026-03-13T08:00:00Z" },
  { id: "e25", ticket_id: "t7", event_type: "NOTE",          actor: "Hassan Ali",    note: "Parts needed: new wiring sleeve and junction box. Ordered, arriving tomorrow.", created_at: "2026-03-13T09:00:00Z" },

  // TKT-0008
  { id: "e26", ticket_id: "t8", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: hvac, Urgency: medium.",          created_at: "2026-03-10T11:01:00Z" },
  { id: "e27", ticket_id: "t8", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali.",                                                      created_at: "2026-03-10T11:30:00Z" },
  { id: "e28", ticket_id: "t8", event_type: "NOTE",          actor: "Hassan Ali",    note: "Visited site. Fan blade is loose. Need to order replacement part.",             created_at: "2026-03-10T15:00:00Z" },
  { id: "e29", ticket_id: "t8", event_type: "COMPLETED",     actor: "Hassan Ali",    note: "Fan blade tightened and motor lubricated. Unit running quietly. Job done.",     created_at: "2026-03-11T13:00:00Z" },

  // TKT-0009
  { id: "e30", ticket_id: "t9", event_type: "CREATED",       actor: "Manager",       note: "Ticket logged manually after tenant called office.",                            created_at: "2026-03-12T14:01:00Z" },
  { id: "e31", ticket_id: "t9", event_type: "NOTE",          actor: "Manager",       note: "Tenant unavailable this week until Friday. Scheduled for Fri 13 March AM.",    created_at: "2026-03-12T14:30:00Z" },
  { id: "e32", ticket_id: "t9", event_type: "NOTE",          actor: "Manager",       note: "Reminded Tariq Saeed to bring sliding door track kit for this job.",           created_at: "2026-03-13T08:00:00Z" },

  // TKT-0010
  { id: "e33", ticket_id: "t10", event_type: "CREATED",      actor: "System (AI)",   note: "Ticket created from WhatsApp. Job type: plumbing, Urgency: medium.",           created_at: "2026-03-12T16:31:00Z" },
  { id: "e34", ticket_id: "t10", event_type: "ASSIGNED",     actor: "Manager",       note: "Assigned to Khalid Rashid. Visit booked for tomorrow morning.",                 created_at: "2026-03-13T09:00:00Z" },
  { id: "e35", ticket_id: "t10", event_type: "NOTE",         actor: "Khalid Rashid", note: "Tenant confirmed access via building concierge after 5pm. Will check thermostat and heating element.", created_at: "2026-03-13T09:30:00Z" },
  { id: "e36", ticket_id: "t10", event_type: "NOTE",         actor: "Manager",       note: "This is the second time this unit has had water heater issues. Flag for full replacement review.", created_at: "2026-03-13T10:00:00Z" },
];