import { Customer, Worker, Ticket, TicketEvent } from "../types/index";

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    full_name: "Ahmed Al Mansoori",
    email: "ahmed.mansoori@email.com",
    phone: "+971501234567",
    property_ref: "Villa-12",
    building_name: "Al Reef Villas",
    floor: null,
    unit_number: "Villa 12",
    area: "Khalifa City",
    city: "Abu Dhabi",
    emergency_contact: "+971509876543",
    contract_expiry: "2026-12-31",
    preferred_contact: "whatsapp",
  },
  {
    id: "c2",
    full_name: "Sara Ibrahim",
    email: "sara.ibrahim@email.com",
    phone: "+971502345678",
    property_ref: "Apt-B7",
    building_name: "The Greens Tower B",
    floor: "7th Floor",
    unit_number: "Apt B7",
    area: "Al Barsha",
    city: "Dubai",
    emergency_contact: null,
    contract_expiry: "2026-04-05",
    preferred_contact: "email",
  },
  {
    id: "c3",
    full_name: "Omar Farooq",
    email: "omar.farooq@email.com",
    phone: "+971503456789",
    property_ref: "Villa-34",
    building_name: "Bloom Gardens",
    floor: null,
    unit_number: "Villa 34",
    area: "Khalifa City",
    city: "Abu Dhabi",
    emergency_contact: "+971508765432",
    contract_expiry: "2027-01-15",
    preferred_contact: "phone",
  },
  {
    id: "c4",
    full_name: "Fatima Noor",
    email: "fatima.noor@email.com",
    phone: "+971504567890",
    property_ref: "Apt-C3",
    building_name: "Reva Residences",
    floor: "3rd Floor",
    unit_number: "Apt C3",
    area: "Al Reem Island",
    city: "Abu Dhabi",
    emergency_contact: null,
    contract_expiry: "2026-03-28",
    preferred_contact: "whatsapp",
  },
  {
    id: "c5",
    full_name: "Rania Hassan",
    email: "rania.hassan@email.com",
    phone: "+971505678901",
    property_ref: "Villa-08",
    building_name: "Mirdif Villas",
    floor: null,
    unit_number: "Villa 8",
    area: "Mirdif",
    city: "Dubai",
    emergency_contact: "+971507654321",
    contract_expiry: "2026-09-30",
    preferred_contact: "email",
  },
  {
    id: "c6",
    full_name: "Yousef Al Zaabi",
    email: "yousef.zaabi@email.com",
    phone: "+971506789012",
    property_ref: "Apt-D11",
    building_name: "Sharjah Gate Towers",
    floor: "11th Floor",
    unit_number: "Apt D11",
    area: "Sharjah Al Majaz",
    city: "Sharjah",
    emergency_contact: null,
    contract_expiry: "2026-07-20",
    preferred_contact: "phone",
  },
  {
    id: "c7",
    full_name: "Layla Mahmoud",
    email: "layla.mahmoud@email.com",
    phone: "+971507890123",
    property_ref: "Villa-21",
    building_name: "Jumeirah Park Villas",
    floor: null,
    unit_number: "Villa 21",
    area: "Jumeirah",
    city: "Dubai",
    emergency_contact: "+971506543210",
    contract_expiry: "2026-04-10",
    preferred_contact: "whatsapp",
  },
  {
    id: "c8",
    full_name: "Bilal Qureshi",
    email: "bilal.qureshi@email.com",
    phone: "+971508901234",
    property_ref: "Apt-A2",
    building_name: "Silicon Heights",
    floor: "2nd Floor",
    unit_number: "Apt A2",
    area: "Dubai Silicon Oasis",
    city: "Dubai",
    emergency_contact: null,
    contract_expiry: "2027-03-01",
    preferred_contact: "email",
  },
  {
    id: "c9",
    full_name: "Mariam Al Ketbi",
    email: "mariam.ketbi@email.com",
    phone: "+971509012345",
    property_ref: "Villa-55",
    building_name: "Al Nahda Gardens",
    floor: null,
    unit_number: "Villa 55",
    area: "Al Nahda",
    city: "Sharjah",
    emergency_contact: "+971505432109",
    contract_expiry: "2026-11-15",
    preferred_contact: "phone",
  },
  {
    id: "c10",
    full_name: "Tariq Bin Zayed",
    email: "tariq.binzayed@email.com",
    phone: "+971500123456",
    property_ref: "Apt-F6",
    building_name: "Bloom Heights",
    floor: "6th Floor",
    unit_number: "Apt F6",
    area: "Al Reem Island",
    city: "Abu Dhabi",
    emergency_contact: null,
    contract_expiry: "2026-08-22",
    preferred_contact: "whatsapp",
  },
];

export const mockWorkers: Worker[] = [
  { id: "w1", full_name: "Khalid Rashid",   skills: ["plumbing", "general"],    phone: "+971501111111", is_active: true,  open_tickets: 3 },
  { id: "w2", full_name: "Hassan Ali",      skills: ["electrical", "hvac"],     phone: "+971502222222", is_active: true,  open_tickets: 5 },
  { id: "w3", full_name: "Tariq Saeed",     skills: ["carpentry", "general"],   phone: "+971503333333", is_active: true,  open_tickets: 1 },
  { id: "w4", full_name: "Mohammed Nasser", skills: ["hvac", "plumbing"],       phone: "+971504444444", is_active: false, open_tickets: 0 },
];

export const mockTickets: Ticket[] = [
  // ─── TKT-0001 | OPEN | high | plumbing | 5 days old → OVERDUE ───────────────
  {
    id: "t1",
    ticket_ref: "TKT-0001",
    customer_email: "ahmed.mansoori@email.com",
    worker_id: null,
    property: "Villa-12",
    job_type: "plumbing",
    urgency: "high",
    status: "OPEN",
    ai_summary: "Burst pipe under kitchen sink causing active water leakage onto floor. Tenant reports water spreading to adjacent cabinet.",
    eta_description: null,
    location_notes: "Kitchen, under the sink cabinet on the left side",
    access_instructions: "Key with building security. Tenant available after 6pm.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a1", url: "https://placehold.co/600x400/fecaca/991b1b?text=Burst+Pipe", file_type: "image", label: "Burst pipe photo", uploaded_by: "Ahmed Al Mansoori", uploaded_at: "2026-03-11T08:00:00Z" },
      { id: "a2", url: "https://placehold.co/600x400/fecaca/991b1b?text=Water+Damage", file_type: "image", label: "Water damage on floor", uploaded_by: "Ahmed Al Mansoori", uploaded_at: "2026-03-11T08:05:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-11T08:00:00Z",
    updated_at: "2026-03-11T08:00:00Z",
  },

  // ─── TKT-0002 | ASSIGNED | medium | electrical ────────────────────────────────
  {
    id: "t2",
    ticket_ref: "TKT-0002",
    customer_email: "sara.ibrahim@email.com",
    worker_id: "w2",
    property: "Apt-B7",
    job_type: "electrical",
    urgency: "medium",
    status: "ASSIGNED",
    ai_summary: "Power outage in bedroom and living room. Circuit breaker trips every time lights are switched on in those rooms.",
    eta_description: "Within 24 hours",
    location_notes: "Fuse box is in the utility closet near the entrance",
    access_instructions: "Tenant Sara works from home, available any time. Call ahead 30 mins.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a3", url: "https://placehold.co/600x400/e2e8f0/475569?text=Fuse+Box", file_type: "image", label: "Tripped circuit breaker", uploaded_by: "Sara Ibrahim", uploaded_at: "2026-03-13T07:30:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-13T09:00:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-13T07:30:00Z",
    updated_at: "2026-03-13T09:00:00Z",
  },

  // ─── TKT-0003 | IN_PROGRESS | low | hvac ─────────────────────────────────────
  {
    id: "t3",
    ticket_ref: "TKT-0003",
    customer_email: "omar.farooq@email.com",
    worker_id: "w2",
    property: "Villa-34",
    job_type: "hvac",
    urgency: "low",
    status: "IN_PROGRESS",
    ai_summary: "AC unit in master bedroom not cooling effectively. Room temperature stays above 28°C even on full blast. Filter likely blocked.",
    eta_description: "Today afternoon",
    location_notes: "Master bedroom, wall-mounted unit above wardrobe",
    access_instructions: "Gate code is 4521. Tenant Omar is home all day.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a4", url: "https://placehold.co/600x400/e2e8f0/475569?text=AC+Unit", file_type: "image", label: "AC unit master bedroom", uploaded_by: "Omar Farooq", uploaded_at: "2026-03-12T10:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-12T10:30:00Z",
    in_progress_at: "2026-03-13T08:00:00Z",
    done_at: null,
    created_at: "2026-03-12T10:00:00Z",
    updated_at: "2026-03-13T08:00:00Z",
  },

  // ─── TKT-0004 | COMPLETED | low | carpentry ──────────────────────────────────
  {
    id: "t4",
    ticket_ref: "TKT-0004",
    customer_email: "fatima.noor@email.com",
    worker_id: "w3",
    property: "Apt-C3",
    job_type: "carpentry",
    urgency: "low",
    status: "COMPLETED",
    ai_summary: "Broken cabinet door hinge in master bedroom wardrobe. Door hanging loose and cannot be closed properly.",
    eta_description: "Next business day",
    location_notes: "Master bedroom, rightmost wardrobe door",
    access_instructions: "Tenant Fatima works mornings. Best time is after 1pm.",
    reported_via: "manual",
    resolution_notes: "Replaced both hinges on the wardrobe door. Door closes and locks properly. Tenant confirmed satisfied.",
    attachments: [
      { id: "a5", url: "https://placehold.co/600x400/e2e8f0/475569?text=Broken+Hinge", file_type: "image", label: "Broken hinge before repair", uploaded_by: "Fatima Noor", uploaded_at: "2026-03-11T09:00:00Z" },
    ],
    completion_photos: [
      { id: "a6", url: "https://placehold.co/600x400/86efac/166534?text=Fixed+Hinge", file_type: "image", label: "Repaired hinge after replacement", uploaded_by: "Tariq Saeed", uploaded_at: "2026-03-12T14:00:00Z" },
    ],
    assigned_at: "2026-03-11T09:15:00Z",
    in_progress_at: "2026-03-11T10:00:00Z",
    done_at: "2026-03-12T14:00:00Z",
    created_at: "2026-03-11T09:00:00Z",
    updated_at: "2026-03-12T14:00:00Z",
  },

  // ─── TKT-0005 | ASSIGNED | high | plumbing ───────────────────────────────────
  {
    id: "t5",
    ticket_ref: "TKT-0005",
    customer_email: "rania.hassan@email.com",
    worker_id: "w1",
    property: "Villa-08",
    job_type: "plumbing",
    urgency: "high",
    status: "ASSIGNED",
    ai_summary: "Main bathroom drain completely blocked. Water backing up into shower and flooding bathroom floor.",
    eta_description: "Within 4 hours",
    location_notes: "Main bathroom, floor drain next to shower",
    access_instructions: "Spare key with neighbour in Villa 9. Tenant Rania reachable on WhatsApp.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a7", url: "https://placehold.co/600x400/fecaca/991b1b?text=Blocked+Drain", file_type: "image", label: "Blocked drain flooding", uploaded_by: "Rania Hassan", uploaded_at: "2026-03-13T08:45:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-13T09:30:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-13T08:45:00Z",
    updated_at: "2026-03-13T09:30:00Z",
  },

  // ─── TKT-0006 | OPEN | medium | general | 3 days old → OVERDUE ──────────────
  {
    id: "t6",
    ticket_ref: "TKT-0006",
    customer_email: "yousef.zaabi@email.com",
    worker_id: null,
    property: "Apt-D11",
    job_type: "general",
    urgency: "medium",
    status: "OPEN",
    ai_summary: "Front door lock jammed. Tenant unable to lock from outside. Security risk as unit on 11th floor facing main corridor.",
    eta_description: null,
    location_notes: "Main entrance door, deadbolt mechanism",
    access_instructions: "Building management has master key. Yousef works nights, do not visit before 12pm.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a8", url: "https://placehold.co/600x400/e2e8f0/475569?text=Door+Lock", file_type: "image", label: "Jammed door lock", uploaded_by: "Yousef Al Zaabi", uploaded_at: "2026-03-13T09:15:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-13T09:15:00Z",
    updated_at: "2026-03-13T09:15:00Z",
  },

  // ─── TKT-0007 | IN_PROGRESS | high | electrical | fire hazard ────────────────
  {
    id: "t7",
    ticket_ref: "TKT-0007",
    customer_email: "layla.mahmoud@email.com",
    worker_id: "w2",
    property: "Villa-21",
    job_type: "electrical",
    urgency: "high",
    status: "IN_PROGRESS",
    ai_summary: "Exposed wiring found in utility room behind washing machine. Wires frayed and touching wall. Potential fire hazard.",
    eta_description: "Within 2 hours",
    location_notes: "Utility room, behind the washing machine on the right wall",
    access_instructions: "Gate is always open. Layla is home. Mark as urgent on arrival.",
    reported_via: "phone",
    resolution_notes: null,
    attachments: [
      { id: "a9", url: "https://placehold.co/600x400/fecaca/991b1b?text=Exposed+Wiring", file_type: "image", label: "Exposed frayed wires", uploaded_by: "Layla Mahmoud", uploaded_at: "2026-03-11T07:00:00Z" },
      { id: "a10", url: "https://placehold.co/600x400/fecaca/991b1b?text=Fire+Risk+Area", file_type: "image", label: "Scorched wall area near wiring", uploaded_by: "Layla Mahmoud", uploaded_at: "2026-03-11T07:05:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-11T07:15:00Z",
    in_progress_at: "2026-03-13T08:00:00Z",
    done_at: null,
    created_at: "2026-03-11T07:00:00Z",
    updated_at: "2026-03-13T08:00:00Z",
  },

  // ─── TKT-0008 | COMPLETED | medium | hvac ────────────────────────────────────
  {
    id: "t8",
    ticket_ref: "TKT-0008",
    customer_email: "bilal.qureshi@email.com",
    worker_id: "w2",
    property: "Apt-A2",
    job_type: "hvac",
    urgency: "medium",
    status: "COMPLETED",
    ai_summary: "Heating unit making loud rattling noise during operation. Noise starts 10 minutes after turning on and persists.",
    eta_description: "Within 24 hours",
    location_notes: "Living room ceiling unit",
    access_instructions: "Bilal works remotely, home all day. Prefers morning visits.",
    reported_via: "email",
    resolution_notes: "Fan blade was loose causing vibration and rattling. Tightened blade assembly and lubricated motor bearings. Unit now operating quietly.",
    attachments: [
      { id: "a11", url: "https://placehold.co/600x400/e2e8f0/475569?text=HVAC+Unit", file_type: "image", label: "Noisy HVAC unit", uploaded_by: "Bilal Qureshi", uploaded_at: "2026-03-10T11:00:00Z" },
    ],
    completion_photos: [
      { id: "a12", url: "https://placehold.co/600x400/86efac/166534?text=Fixed+HVAC", file_type: "image", label: "Repaired fan assembly", uploaded_by: "Hassan Ali", uploaded_at: "2026-03-11T13:00:00Z" },
    ],
    assigned_at: "2026-03-10T11:30:00Z",
    in_progress_at: "2026-03-10T15:00:00Z",
    done_at: "2026-03-11T13:00:00Z",
    created_at: "2026-03-10T11:00:00Z",
    updated_at: "2026-03-11T13:00:00Z",
  },

  // ─── TKT-0009 | OPEN | low | carpentry | 4 days old → OVERDUE ───────────────
  {
    id: "t9",
    ticket_ref: "TKT-0009",
    customer_email: "mariam.ketbi@email.com",
    worker_id: null,
    property: "Villa-55",
    job_type: "carpentry",
    urgency: "low",
    status: "OPEN",
    ai_summary: "Wardrobe sliding door has come off its track in second bedroom. Door cannot be moved and is blocking access to wardrobe.",
    eta_description: null,
    location_notes: "Second bedroom, built-in wardrobe sliding door",
    access_instructions: "Call Mariam 1 hour before. Property has a dog — knock loudly.",
    reported_via: "manual",
    resolution_notes: null,
    attachments: [
      { id: "a13", url: "https://placehold.co/600x400/e2e8f0/475569?text=Wardrobe+Door", file_type: "image", label: "Sliding door off track", uploaded_by: "Mariam Al Ketbi", uploaded_at: "2026-03-12T14:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-12T14:00:00Z",
    updated_at: "2026-03-12T14:00:00Z",
  },

  // ─── TKT-0010 | ASSIGNED | medium | plumbing ─────────────────────────────────
  {
    id: "t10",
    ticket_ref: "TKT-0010",
    customer_email: "tariq.binzayed@email.com",
    worker_id: "w1",
    property: "Apt-F6",
    job_type: "plumbing",
    urgency: "medium",
    status: "ASSIGNED",
    ai_summary: "Water heater not producing consistent hot water. Water runs warm for 2 minutes then turns cold. Issue recurring since last month.",
    eta_description: "Tomorrow morning",
    location_notes: "Utility cupboard next to bathroom, white tank unit",
    access_instructions: "Tariq is available after 5pm weekdays. Building concierge has spare key.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a14", url: "https://placehold.co/600x400/e2e8f0/475569?text=Water+Heater", file_type: "image", label: "Water heater unit", uploaded_by: "Tariq Bin Zayed", uploaded_at: "2026-03-12T16:30:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-13T09:00:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-12T16:30:00Z",
    updated_at: "2026-03-13T09:00:00Z",
  },

  // ─── TKT-0011 | COMPLETED | low | general | 2 weeks ago ─────────────────────
  {
    id: "t11",
    ticket_ref: "TKT-0011",
    customer_email: "ahmed.mansoori@email.com",
    worker_id: "w3",
    property: "Villa-12",
    job_type: "general",
    urgency: "low",
    status: "COMPLETED",
    ai_summary: "Window seal in living room cracked along the bottom edge, causing noticeable draft and minor water seepage during heavy rain.",
    eta_description: "Within 2 business days",
    location_notes: "Living room, large sliding window facing garden",
    access_instructions: "Ahmed available weekends and evenings. Gate always unlocked during daytime.",
    reported_via: "whatsapp",
    resolution_notes: "Removed old cracked seal and applied new EPDM weatherstrip along full window perimeter. Water-tested with hose — no leakage. Tenant satisfied.",
    attachments: [
      { id: "a15", url: "https://placehold.co/600x400/e2e8f0/475569?text=Cracked+Seal", file_type: "image", label: "Cracked window seal", uploaded_by: "Ahmed Al Mansoori", uploaded_at: "2026-02-28T09:00:00Z" },
    ],
    completion_photos: [
      { id: "a16", url: "https://placehold.co/600x400/86efac/166534?text=New+Seal+Applied", file_type: "image", label: "New weatherstrip installed", uploaded_by: "Tariq Saeed", uploaded_at: "2026-03-01T14:00:00Z" },
    ],
    assigned_at: "2026-02-28T10:00:00Z",
    in_progress_at: "2026-03-01T09:00:00Z",
    done_at: "2026-03-01T14:00:00Z",
    created_at: "2026-02-28T09:00:00Z",
    updated_at: "2026-03-01T14:00:00Z",
  },

  // ─── TKT-0012 | OPEN | high | plumbing | yesterday ───────────────────────────
  {
    id: "t12",
    ticket_ref: "TKT-0012",
    customer_email: "sara.ibrahim@email.com",
    worker_id: null,
    property: "Apt-B7",
    job_type: "plumbing",
    urgency: "high",
    status: "OPEN",
    ai_summary: "Kitchen tap dripping heavily and cannot be turned off. Drip rate has increased over 24 hours. Tenant concerned about water bill and potential cabinet damage.",
    eta_description: null,
    location_notes: "Kitchen, main sink tap — both hot and cold sides dripping",
    access_instructions: "Sara is home all day. Prefers technician to call before arriving. Apartment on 7th floor, use elevator B.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a17", url: "https://placehold.co/600x400/fecaca/991b1b?text=Dripping+Tap", file_type: "image", label: "Heavy drip from kitchen tap", uploaded_by: "Sara Ibrahim", uploaded_at: "2026-03-15T14:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-15T14:00:00Z",
    updated_at: "2026-03-15T14:00:00Z",
  },

  // ─── TKT-0013 | COMPLETED | medium | carpentry | 3 weeks ago ────────────────
  {
    id: "t13",
    ticket_ref: "TKT-0013",
    customer_email: "omar.farooq@email.com",
    worker_id: "w3",
    property: "Villa-34",
    job_type: "carpentry",
    urgency: "medium",
    status: "COMPLETED",
    ai_summary: "Two kitchen cabinet doors warped and severely misaligned due to humidity. Doors will not close fully and gap allows pests to enter.",
    eta_description: "Within 3 days",
    location_notes: "Kitchen, upper cabinet row — second and fourth doors from the left",
    access_instructions: "Gate code is 4521. Omar works from home and is usually available.",
    reported_via: "phone",
    resolution_notes: "Planed down swollen door edges and readjusted all hinges. Applied wood sealant to prevent future warping. Both doors closing and latching correctly.",
    attachments: [
      { id: "a18", url: "https://placehold.co/600x400/e2e8f0/475569?text=Warped+Doors", file_type: "image", label: "Warped cabinet doors", uploaded_by: "Omar Farooq", uploaded_at: "2026-02-20T11:00:00Z" },
    ],
    completion_photos: [
      { id: "a19", url: "https://placehold.co/600x400/86efac/166534?text=Doors+Fixed", file_type: "image", label: "Cabinet doors after repair", uploaded_by: "Tariq Saeed", uploaded_at: "2026-02-22T15:00:00Z" },
    ],
    assigned_at: "2026-02-21T09:00:00Z",
    in_progress_at: "2026-02-22T09:00:00Z",
    done_at: "2026-02-22T15:00:00Z",
    created_at: "2026-02-20T11:00:00Z",
    updated_at: "2026-02-22T15:00:00Z",
  },

  // ─── TKT-0014 | IN_PROGRESS | low | electrical ───────────────────────────────
  {
    id: "t14",
    ticket_ref: "TKT-0014",
    customer_email: "fatima.noor@email.com",
    worker_id: "w2",
    property: "Apt-C3",
    job_type: "electrical",
    urgency: "low",
    status: "IN_PROGRESS",
    ai_summary: "Single wall socket in study room not working. Tenant confirms other sockets in the room work fine. Possibly a tripped internal RCCD or loose connection.",
    eta_description: "Today afternoon",
    location_notes: "Study room, double socket on the east wall behind the desk",
    access_instructions: "Fatima available after 1pm. Building entrance requires intercom buzz — call +971504567890 on arrival.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a20", url: "https://placehold.co/600x400/e2e8f0/475569?text=Dead+Socket", file_type: "image", label: "Non-functional wall socket", uploaded_by: "Fatima Noor", uploaded_at: "2026-03-14T10:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-14T11:00:00Z",
    in_progress_at: "2026-03-15T10:00:00Z",
    done_at: null,
    created_at: "2026-03-14T10:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
  },

  // ─── TKT-0015 | IN_PROGRESS | high | hvac | total AC failure ─────────────────
  {
    id: "t15",
    ticket_ref: "TKT-0015",
    customer_email: "rania.hassan@email.com",
    worker_id: "w2",
    property: "Villa-08",
    job_type: "hvac",
    urgency: "high",
    status: "IN_PROGRESS",
    ai_summary: "Total AC failure across all three bedroom units simultaneously. No airflow or cooling. External compressor unit making grinding noise before shutting off. Home is currently unlivable in heat.",
    eta_description: "Same day",
    location_notes: "All bedroom units — master, second, and third bedrooms. External compressor unit on roof terrace.",
    access_instructions: "Spare key with neighbour Villa 9. Rania also available on site. Mark as urgent — tenant has infant child.",
    reported_via: "phone",
    resolution_notes: null,
    attachments: [
      { id: "a21", url: "https://placehold.co/600x400/fecaca/991b1b?text=AC+Failure", file_type: "image", label: "All AC units offline", uploaded_by: "Rania Hassan", uploaded_at: "2026-03-15T07:00:00Z" },
      { id: "a22", url: "https://placehold.co/600x400/fecaca/991b1b?text=Compressor+Unit", file_type: "image", label: "Grinding compressor on roof", uploaded_by: "Rania Hassan", uploaded_at: "2026-03-15T07:10:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-15T08:00:00Z",
    in_progress_at: "2026-03-15T11:00:00Z",
    done_at: null,
    created_at: "2026-03-15T07:00:00Z",
    updated_at: "2026-03-15T11:00:00Z",
  },

  // ─── TKT-0016 | COMPLETED | low | carpentry | last week ─────────────────────
  {
    id: "t16",
    ticket_ref: "TKT-0016",
    customer_email: "yousef.zaabi@email.com",
    worker_id: "w3",
    property: "Apt-D11",
    job_type: "carpentry",
    urgency: "low",
    status: "COMPLETED",
    ai_summary: "Bathroom vanity cabinet shelf bracket snapped under weight. Shelf has collapsed inside the cabinet, contents damaged.",
    eta_description: "Within 2 days",
    location_notes: "Master bathroom, vanity cabinet — middle shelf bracket on left side",
    access_instructions: "Building management holds master key. Yousef works nights, visit must be after 12pm.",
    reported_via: "whatsapp",
    resolution_notes: "Removed broken bracket and installed heavy-duty replacement pair. Shelf re-levelled and load-tested. Tenant confirmed all contents returned and cabinet in good order.",
    attachments: [
      { id: "a23", url: "https://placehold.co/600x400/e2e8f0/475569?text=Broken+Bracket", file_type: "image", label: "Snapped shelf bracket", uploaded_by: "Yousef Al Zaabi", uploaded_at: "2026-03-05T13:00:00Z" },
    ],
    completion_photos: [
      { id: "a24", url: "https://placehold.co/600x400/86efac/166534?text=New+Brackets", file_type: "image", label: "New brackets installed", uploaded_by: "Tariq Saeed", uploaded_at: "2026-03-06T12:00:00Z" },
    ],
    assigned_at: "2026-03-06T09:00:00Z",
    in_progress_at: "2026-03-06T10:00:00Z",
    done_at: "2026-03-06T12:00:00Z",
    created_at: "2026-03-05T13:00:00Z",
    updated_at: "2026-03-06T12:00:00Z",
  },

  // ─── TKT-0017 | ASSIGNED | medium | plumbing ─────────────────────────────────
  {
    id: "t17",
    ticket_ref: "TKT-0017",
    customer_email: "layla.mahmoud@email.com",
    worker_id: "w1",
    property: "Villa-21",
    job_type: "plumbing",
    urgency: "medium",
    status: "ASSIGNED",
    ai_summary: "Kitchen sink draining very slowly — full sink takes over 15 minutes to empty. Likely grease and debris buildup in drain pipe.",
    eta_description: "Tomorrow morning",
    location_notes: "Kitchen, sink drain — under the sink U-bend may also need clearing",
    access_instructions: "Gate always open. Layla is home most mornings. Afternoon visits require a call ahead.",
    reported_via: "whatsapp",
    resolution_notes: null,
    attachments: [
      { id: "a25", url: "https://placehold.co/600x400/e2e8f0/475569?text=Slow+Drain", file_type: "image", label: "Slow kitchen drain", uploaded_by: "Layla Mahmoud", uploaded_at: "2026-03-14T16:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-15T09:00:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-14T16:00:00Z",
    updated_at: "2026-03-15T09:00:00Z",
  },

  // ─── TKT-0018 | OPEN | high | electrical | OVERDUE (>24 hrs, no worker) ──────
  {
    id: "t18",
    ticket_ref: "TKT-0018",
    customer_email: "bilal.qureshi@email.com",
    worker_id: null,
    property: "Apt-A2",
    job_type: "electrical",
    urgency: "high",
    status: "OPEN",
    ai_summary: "Visible sparks emitting from master bedroom wall socket when devices are plugged in. Strong burnt plastic smell. Possible short circuit or overloaded circuit. Safety hazard — tenant has switched off main breaker.",
    eta_description: null,
    location_notes: "Master bedroom, double socket on wall opposite the bed",
    access_instructions: "Bilal is home all day. Main breaker is currently OFF — restore with care. Apartment 2nd floor, Silicon Heights lobby.",
    reported_via: "phone",
    resolution_notes: null,
    attachments: [
      { id: "a26", url: "https://placehold.co/600x400/fecaca/991b1b?text=Sparking+Socket", file_type: "image", label: "Sparking socket with burn marks", uploaded_by: "Bilal Qureshi", uploaded_at: "2026-03-14T22:00:00Z" },
      { id: "a27", url: "https://placehold.co/600x400/fecaca/991b1b?text=Burnt+Smell+Area", file_type: "image", label: "Scorched socket surround", uploaded_by: "Bilal Qureshi", uploaded_at: "2026-03-14T22:05:00Z" },
    ],
    completion_photos: [],
    assigned_at: null,
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-14T22:00:00Z",
    updated_at: "2026-03-14T22:00:00Z",
  },

  // ─── TKT-0019 | ASSIGNED | low | general ─────────────────────────────────────
  {
    id: "t19",
    ticket_ref: "TKT-0019",
    customer_email: "mariam.ketbi@email.com",
    worker_id: "w3",
    property: "Villa-55",
    job_type: "general",
    urgency: "low",
    status: "ASSIGNED",
    ai_summary: "Long diagonal crack on exterior wall near garage entrance. Approximately 1.2 metres in length. Cosmetic at present but requires structural assessment before next rainy season.",
    eta_description: "This week",
    location_notes: "Exterior wall, left side of garage entrance — visible from driveway",
    access_instructions: "Call Mariam 1 hour before arrival. Dog will be secured indoors. Driveway access available.",
    reported_via: "email",
    resolution_notes: null,
    attachments: [
      { id: "a28", url: "https://placehold.co/600x400/e2e8f0/475569?text=Wall+Crack", file_type: "image", label: "Exterior wall crack near garage", uploaded_by: "Mariam Al Ketbi", uploaded_at: "2026-03-13T15:00:00Z" },
    ],
    completion_photos: [],
    assigned_at: "2026-03-14T09:00:00Z",
    in_progress_at: null,
    done_at: null,
    created_at: "2026-03-13T15:00:00Z",
    updated_at: "2026-03-14T09:00:00Z",
  },

  // ─── TKT-0020 | COMPLETED | medium | hvac | last week ───────────────────────
  {
    id: "t20",
    ticket_ref: "TKT-0020",
    customer_email: "tariq.binzayed@email.com",
    worker_id: "w2",
    property: "Apt-F6",
    job_type: "hvac",
    urgency: "medium",
    status: "COMPLETED",
    ai_summary: "AC unit in guest bedroom not responding to remote control. Unit powers on manually from wall switch but temperature and mode cannot be adjusted remotely.",
    eta_description: "Within 2 days",
    location_notes: "Guest bedroom, wall-mounted split unit above window",
    access_instructions: "Tariq available after 5pm weekdays. Building concierge has spare key for daytime access.",
    reported_via: "email",
    resolution_notes: "Diagnosed faulty infrared sensor board on the indoor unit. Replaced sensor PCB with OEM part. Remote control fully functional across all modes. Tested cooling, fan, and timer functions.",
    attachments: [
      { id: "a29", url: "https://placehold.co/600x400/e2e8f0/475569?text=AC+Remote+Issue", file_type: "image", label: "AC unit not responding to remote", uploaded_by: "Tariq Bin Zayed", uploaded_at: "2026-03-08T14:00:00Z" },
    ],
    completion_photos: [
      { id: "a30", url: "https://placehold.co/600x400/86efac/166534?text=Remote+Working", file_type: "image", label: "AC responding to remote after repair", uploaded_by: "Hassan Ali", uploaded_at: "2026-03-09T13:00:00Z" },
    ],
    assigned_at: "2026-03-09T09:00:00Z",
    in_progress_at: "2026-03-09T10:00:00Z",
    done_at: "2026-03-09T13:00:00Z",
    created_at: "2026-03-08T14:00:00Z",
    updated_at: "2026-03-09T13:00:00Z",
  },
];

export const mockTicketEvents: TicketEvent[] = [
  // TKT-0001 (OPEN, overdue)
  { id: "e1",  ticket_id: "t1",  event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: plumbing, Urgency: high.",                            created_at: "2026-03-11T08:01:00Z" },
  { id: "e2",  ticket_id: "t1",  event_type: "NOTE",          actor: "Manager",       note: "Called tenant. Water shutoff valve closed temporarily to stop leak. Awaiting worker assignment.",   created_at: "2026-03-11T08:30:00Z" },
  { id: "e3",  ticket_id: "t1",  event_type: "NOTE",          actor: "Manager",       note: "No available plumber today. Escalated for tomorrow morning slot. Tenant informed.",                 created_at: "2026-03-11T17:00:00Z" },
  { id: "e4",  ticket_id: "t1",  event_type: "NOTE",          actor: "Manager",       note: "Still unassigned — Khalid is at capacity. Checking if Mohammed can be reactivated for this job.",   created_at: "2026-03-13T09:00:00Z" },

  // TKT-0002 (ASSIGNED)
  { id: "e5",  ticket_id: "t2",  event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: electrical, Urgency: medium.",                         created_at: "2026-03-13T07:31:00Z" },
  { id: "e6",  ticket_id: "t2",  event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali. ETA within 24 hours.",                                                     created_at: "2026-03-13T09:00:00Z" },
  { id: "e7",  ticket_id: "t2",  event_type: "NOTE",          actor: "Hassan Ali",    note: "On my way to site. Estimated arrival in 45 minutes.",                                               created_at: "2026-03-13T09:15:00Z" },
  { id: "e8",  ticket_id: "t2",  event_type: "NOTE",          actor: "Manager",       note: "Tenant Sara confirmed she is home and ready for technician.",                                       created_at: "2026-03-13T09:20:00Z" },

  // TKT-0003 (IN_PROGRESS)
  { id: "e9",  ticket_id: "t3",  event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp message. Job type: hvac, Urgency: low.",                              created_at: "2026-03-12T10:01:00Z" },
  { id: "e10", ticket_id: "t3",  event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali. Scheduled for this afternoon.",                                            created_at: "2026-03-12T10:30:00Z" },
  { id: "e11", ticket_id: "t3",  event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "Arrived on site. Filter is heavily blocked with dust. Cleaning filter now.",                        created_at: "2026-03-13T08:00:00Z" },
  { id: "e12", ticket_id: "t3",  event_type: "NOTE",          actor: "Hassan Ali",    note: "Filter cleaned and reinstalled. Testing cooling performance. Will confirm fix in 30 minutes.",      created_at: "2026-03-13T08:45:00Z" },

  // TKT-0004 (COMPLETED)
  { id: "e13", ticket_id: "t4",  event_type: "CREATED",       actor: "Manager",       note: "Ticket created manually by manager after tenant called office.",                                    created_at: "2026-03-11T09:01:00Z" },
  { id: "e14", ticket_id: "t4",  event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Tariq Saeed. Visit scheduled for next morning.",                                       created_at: "2026-03-11T09:15:00Z" },
  { id: "e15", ticket_id: "t4",  event_type: "NOTE",          actor: "Tariq Saeed",   note: "Tenant confirmed access for tomorrow at 10am.",                                                    created_at: "2026-03-11T14:00:00Z" },
  { id: "e16", ticket_id: "t4",  event_type: "STATUS_CHANGE", actor: "Tariq Saeed",   note: "On site. Both hinges cracked — replacing full set.",                                               created_at: "2026-03-12T10:00:00Z" },
  { id: "e17", ticket_id: "t4",  event_type: "COMPLETED",     actor: "Tariq Saeed",   note: "Both hinges replaced. Door operates correctly. Tenant signed off on completion.",                   created_at: "2026-03-12T14:00:00Z" },

  // TKT-0005 (ASSIGNED)
  { id: "e18", ticket_id: "t5",  event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp. Job type: plumbing, Urgency: high.",                                 created_at: "2026-03-13T08:46:00Z" },
  { id: "e19", ticket_id: "t5",  event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Khalid Rashid as highest priority. ETA 4 hours.",                                      created_at: "2026-03-13T09:30:00Z" },
  { id: "e20", ticket_id: "t5",  event_type: "NOTE",          actor: "Khalid Rashid", note: "Confirmed with tenant. Heading to site now. Will need drain snake equipment.",                      created_at: "2026-03-13T09:45:00Z" },

  // TKT-0006 (OPEN, overdue)
  { id: "e21", ticket_id: "t6",  event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: general, Urgency: medium.",                           created_at: "2026-03-13T09:16:00Z" },
  { id: "e22", ticket_id: "t6",  event_type: "NOTE",          actor: "Manager",       note: "Noted tenant works nights. Scheduling visit for after 12pm tomorrow.",                              created_at: "2026-03-13T10:00:00Z" },
  { id: "e23", ticket_id: "t6",  event_type: "NOTE",          actor: "Manager",       note: "Building management informed to ensure master key available for technician.",                       created_at: "2026-03-13T10:05:00Z" },
  { id: "e24", ticket_id: "t6",  event_type: "NOTE",          actor: "Manager",       note: "Still unassigned. Tariq is on other jobs. Will prioritise tomorrow.",                               created_at: "2026-03-15T09:00:00Z" },

  // TKT-0007 (IN_PROGRESS, fire hazard)
  { id: "e25", ticket_id: "t7",  event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from phone call log. Job type: electrical, Urgency: high.",                         created_at: "2026-03-11T07:01:00Z" },
  { id: "e26", ticket_id: "t7",  event_type: "ASSIGNED",      actor: "Manager",       note: "Marked critical. Assigned to Hassan Ali immediately.",                                              created_at: "2026-03-11T07:15:00Z" },
  { id: "e27", ticket_id: "t7",  event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "On site. Wiring is exposed and dangerous. Isolated the circuit for safety.",                        created_at: "2026-03-13T08:00:00Z" },
  { id: "e28", ticket_id: "t7",  event_type: "NOTE",          actor: "Hassan Ali",    note: "Parts ordered: new wiring sleeve and junction box. Arriving tomorrow. Tenant advised not to use utility room.", created_at: "2026-03-13T09:00:00Z" },
  { id: "e29", ticket_id: "t7",  event_type: "NOTE",          actor: "Manager",       note: "Parts confirmed delivered to site. Hassan returning tomorrow to complete fix.",                     created_at: "2026-03-15T14:00:00Z" },

  // TKT-0008 (COMPLETED)
  { id: "e30", ticket_id: "t8",  event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: hvac, Urgency: medium.",                              created_at: "2026-03-10T11:01:00Z" },
  { id: "e31", ticket_id: "t8",  event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali.",                                                                          created_at: "2026-03-10T11:30:00Z" },
  { id: "e32", ticket_id: "t8",  event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "Visited site. Fan blade is loose. Need to order replacement part.",                                 created_at: "2026-03-10T15:00:00Z" },
  { id: "e33", ticket_id: "t8",  event_type: "COMPLETED",     actor: "Hassan Ali",    note: "Fan blade tightened and motor lubricated. Unit running quietly. Job done.",                         created_at: "2026-03-11T13:00:00Z" },

  // TKT-0009 (OPEN, overdue)
  { id: "e34", ticket_id: "t9",  event_type: "CREATED",       actor: "Manager",       note: "Ticket logged manually after tenant called office.",                                                created_at: "2026-03-12T14:01:00Z" },
  { id: "e35", ticket_id: "t9",  event_type: "NOTE",          actor: "Manager",       note: "Tenant unavailable until Friday. Scheduled for Friday 13 March AM.",                               created_at: "2026-03-12T14:30:00Z" },
  { id: "e36", ticket_id: "t9",  event_type: "NOTE",          actor: "Manager",       note: "Tariq could not attend Friday — rescheduled to early next week. Tenant notified.",                  created_at: "2026-03-13T17:00:00Z" },

  // TKT-0010 (ASSIGNED)
  { id: "e37", ticket_id: "t10", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp. Job type: plumbing, Urgency: medium.",                               created_at: "2026-03-12T16:31:00Z" },
  { id: "e38", ticket_id: "t10", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Khalid Rashid. Visit booked for tomorrow morning.",                                     created_at: "2026-03-13T09:00:00Z" },
  { id: "e39", ticket_id: "t10", event_type: "NOTE",          actor: "Khalid Rashid", note: "Tenant confirmed access via building concierge after 5pm. Will check thermostat and heating element.", created_at: "2026-03-13T09:30:00Z" },
  { id: "e40", ticket_id: "t10", event_type: "NOTE",          actor: "Manager",       note: "Second reported water heater issue for this unit. Flag for full replacement review after this job.", created_at: "2026-03-13T10:00:00Z" },

  // TKT-0011 (COMPLETED, 2 weeks ago)
  { id: "e41", ticket_id: "t11", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp message. Job type: general, Urgency: low.",                           created_at: "2026-02-28T09:01:00Z" },
  { id: "e42", ticket_id: "t11", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Tariq Saeed. Non-urgent — scheduled for next available slot.",                         created_at: "2026-02-28T10:00:00Z" },
  { id: "e43", ticket_id: "t11", event_type: "STATUS_CHANGE", actor: "Tariq Saeed",   note: "On site. Seal is cracked along full bottom edge. Will replace with EPDM strip.",                   created_at: "2026-03-01T09:00:00Z" },
  { id: "e44", ticket_id: "t11", event_type: "COMPLETED",     actor: "Tariq Saeed",   note: "New weatherstrip applied. Hose-tested with no leakage detected. Tenant confirmed satisfied.",      created_at: "2026-03-01T14:00:00Z" },

  // TKT-0012 (OPEN, yesterday)
  { id: "e45", ticket_id: "t12", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: plumbing, Urgency: high.",                            created_at: "2026-03-15T14:01:00Z" },
  { id: "e46", ticket_id: "t12", event_type: "NOTE",          actor: "Manager",       note: "Reviewed ticket. Khalid currently at capacity. Will assign first thing tomorrow morning.",          created_at: "2026-03-15T14:30:00Z" },

  // TKT-0013 (COMPLETED, 3 weeks ago)
  { id: "e47", ticket_id: "t13", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from phone call. Job type: carpentry, Urgency: medium.",                            created_at: "2026-02-20T11:01:00Z" },
  { id: "e48", ticket_id: "t13", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Tariq Saeed. Scheduled for Friday visit.",                                             created_at: "2026-02-21T09:00:00Z" },
  { id: "e49", ticket_id: "t13", event_type: "STATUS_CHANGE", actor: "Tariq Saeed",   note: "Arrived on site. Both doors heavily swollen. Will plane and re-hang today.",                        created_at: "2026-02-22T09:00:00Z" },
  { id: "e50", ticket_id: "t13", event_type: "COMPLETED",     actor: "Tariq Saeed",   note: "Doors planed, hinges adjusted, sealant applied. All cabinet doors closing correctly. Job done.",    created_at: "2026-02-22T15:00:00Z" },

  // TKT-0014 (IN_PROGRESS)
  { id: "e51", ticket_id: "t14", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp. Job type: electrical, Urgency: low.",                                created_at: "2026-03-14T10:01:00Z" },
  { id: "e52", ticket_id: "t14", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali. Non-urgent — slotted into tomorrow morning round.",                        created_at: "2026-03-14T11:00:00Z" },
  { id: "e53", ticket_id: "t14", event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "On site. Socket has internal RCCD tripped. Checking for underlying cause before resetting.",        created_at: "2026-03-15T10:00:00Z" },

  // TKT-0015 (IN_PROGRESS, urgent)
  { id: "e54", ticket_id: "t15", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound phone call. Job type: hvac, Urgency: high.",                           created_at: "2026-03-15T07:01:00Z" },
  { id: "e55", ticket_id: "t15", event_type: "ASSIGNED",      actor: "Manager",       note: "Critical — all AC units failed. Assigned to Hassan Ali. Override his schedule for this.",           created_at: "2026-03-15T08:00:00Z" },
  { id: "e56", ticket_id: "t15", event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "On site. External compressor capacitor has failed, taking down all indoor units. Part ordered.",    created_at: "2026-03-15T11:00:00Z" },
  { id: "e57", ticket_id: "t15", event_type: "NOTE",          actor: "Hassan Ali",    note: "Tenant has moved to in-laws temporarily. Part arriving tomorrow. Will complete repair first thing.", created_at: "2026-03-15T13:00:00Z" },

  // TKT-0016 (COMPLETED, last week)
  { id: "e58", ticket_id: "t16", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp. Job type: carpentry, Urgency: low.",                                 created_at: "2026-03-05T13:01:00Z" },
  { id: "e59", ticket_id: "t16", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Tariq Saeed. Scheduled for tomorrow afternoon.",                                       created_at: "2026-03-06T09:00:00Z" },
  { id: "e60", ticket_id: "t16", event_type: "STATUS_CHANGE", actor: "Tariq Saeed",   note: "On site. Old bracket snapped clean — replacing with heavy-duty pair.",                              created_at: "2026-03-06T10:00:00Z" },
  { id: "e61", ticket_id: "t16", event_type: "COMPLETED",     actor: "Tariq Saeed",   note: "New brackets installed and load-tested. Shelf stable. Tenant confirmed contents restored.",         created_at: "2026-03-06T12:00:00Z" },

  // TKT-0017 (ASSIGNED)
  { id: "e62", ticket_id: "t17", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from WhatsApp. Job type: plumbing, Urgency: medium.",                               created_at: "2026-03-14T16:01:00Z" },
  { id: "e63", ticket_id: "t17", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Khalid Rashid. Scheduled for tomorrow morning.",                                       created_at: "2026-03-15T09:00:00Z" },
  { id: "e64", ticket_id: "t17", event_type: "NOTE",          actor: "Khalid Rashid", note: "Confirmed with tenant. Will bring drain snake and chemical cleaner.",                               created_at: "2026-03-15T09:15:00Z" },

  // TKT-0018 (OPEN, OVERDUE, high urgency — no worker assigned)
  { id: "e65", ticket_id: "t18", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound phone call. Job type: electrical, Urgency: high.",                     created_at: "2026-03-14T22:01:00Z" },
  { id: "e66", ticket_id: "t18", event_type: "NOTE",          actor: "Manager",       note: "Reviewed overnight. Hassan and Khalid both at capacity. Assigning to Mohammed (reactivating) or escalating externally.", created_at: "2026-03-15T08:00:00Z" },
  { id: "e67", ticket_id: "t18", event_type: "NOTE",          actor: "Manager",       note: "Still unresolved. Bilal has shut off main breaker — apartment without power. Escalating to emergency contractor.", created_at: "2026-03-16T09:00:00Z" },

  // TKT-0019 (ASSIGNED)
  { id: "e68", ticket_id: "t19", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: general, Urgency: low.",                              created_at: "2026-03-13T15:01:00Z" },
  { id: "e69", ticket_id: "t19", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Tariq Saeed for structural assessment this week.",                                      created_at: "2026-03-14T09:00:00Z" },
  { id: "e70", ticket_id: "t19", event_type: "NOTE",          actor: "Tariq Saeed",   note: "Reviewed photos. Looks cosmetic but will inspect in person to confirm no structural risk.",         created_at: "2026-03-14T09:30:00Z" },

  // TKT-0020 (COMPLETED, last week)
  { id: "e71", ticket_id: "t20", event_type: "CREATED",       actor: "System (AI)",   note: "Ticket created from inbound email. Job type: hvac, Urgency: medium.",                              created_at: "2026-03-08T14:01:00Z" },
  { id: "e72", ticket_id: "t20", event_type: "ASSIGNED",      actor: "Manager",       note: "Assigned to Hassan Ali. Scheduled for tomorrow morning.",                                           created_at: "2026-03-09T09:00:00Z" },
  { id: "e73", ticket_id: "t20", event_type: "STATUS_CHANGE", actor: "Hassan Ali",    note: "On site. IR sensor board on indoor unit is faulty. Replacing with OEM part.",                       created_at: "2026-03-09T10:00:00Z" },
  { id: "e74", ticket_id: "t20", event_type: "COMPLETED",     actor: "Hassan Ali",    note: "Sensor PCB replaced. Remote control working across all modes — cooling, fan, timer. Job done.",     created_at: "2026-03-09T13:00:00Z" },
];
